.gitignore
Vagrantfile.example
provision.sh
requirements.txt

setting: initial vagrant

---

lintcode/457-Classical-Binary-Search/solution.py
lintcode/457-Classical-Binary-Search/test.py

- lintcode: 457-Classical-Binary-Search
- https://www.lintcode.com/problem/457/

lintcode: 457-Classical-Binary-Search

---

lintcode/458-Last-Position-of-Target/solution.py
lintcode/458-Last-Position-of-Target/test.py

- lintcode: 458-Last-Position-of-Target
- https://www.lintcode.com/problem/458/

lintcode: 458-Last-Position-of-Target

---

lintcode/14-First-Position-of-Target/solution.py
lintcode/14-First-Position-of-Target/test.py

- lintcode: 14-First-Position-of-Target
- https://www.lintcode.com/problem/14/

lintcode: 14-First-Position-of-Target

---

.travis.yml
README.md

- setting: initial .travis.yml

setting: initial .travis.yml

---

.travis.yml

setting: initial codacy

---

lintcode/binary_search/248-Count-of-Smaller-Number/solution.py
lintcode/binary_search/248-Count-of-Smaller-Number/test.py

- lintcode: 248-Count-of-Smaller-Number

lintcode: 248-Count-of-Smaller-Number

---

lintcode/binary_search/61-Search-for-a-Range/solution.py
lintcode/binary_search/61-Search-for-a-Range/test.py

- lintcode: 61-Search-for-a-Range

lintcode: 61-Search-for-a-Range

---

lintcode/binary_search/159-Find-Minimum-in-Rotated-Sorted-Array/solution.py
lintcode/binary_search/159-Find-Minimum-in-Rotated-Sorted-Array/test.py

- lintcode: 159-Find-Minimum-in-Rotated-Sorted-Array

lintcode: 159-Find-Minimum-in-Rotated-Sorted-Array

---

lintcode/binary_search/585-Maximum-Number-in-Mountain-Sequence/solution.py
lintcode/binary_search/585-Maximum-Number-in-Mountain-Sequence/test.py

- lintcode: 585-Maximum-Number-in-Mountain-Sequence

lintcode: 585-Maximum-Number-in-Mountain-Sequence

---

lintcode/binary_search/75-Find-Peak-Element/solution.py
lintcode/binary_search/75-Find-Peak-Element/test.py

- lintcode: 75-Find-Peak-Element

lintcode: 75-Find-Peak-Element

---

lintcode/binary_search/62-Search-in-Rotated-Sorted-Array/solution.py
lintcode/binary_search/62-Search-in-Rotated-Sorted-Array/test.py

- lintcode: 62-Search-in-Rotated-Sorted-Array

lintcode: 62-Search-in-Rotated-Sorted-Array

---

lintcode/two_pointers/604-Window-Sum/solution.py
lintcode/two_pointers/604-Window-Sum/test.py

lintcode: 604-Window-Sum

---

lintcode/two_pointers/539-Move-Zeroes/solution.py
lintcode/two_pointers/539-Move-Zeroes/test.py

lintcode: 539-Move-Zeroes

---

lintcode/two_pointers/521-Remove-Duplicate-Numbers-in-Array/solution.py
lintcode/two_pointers/521-Remove-Duplicate-Numbers-in-Array/test.py

- lintcode: 521-Remove-Duplicate-Numbers-in-Array

lintcode: 521-Remove-Duplicate-Numbers-in-Array

---

lintcode/two_pointers/608-Two-Sum-II-Input-array-is-sorted/solution.py
lintcode/two_pointers/608-Two-Sum-II-Input-array-is-sorted/test.py

lintcode: 608-Two-Sum-II-Input-array-is-sorted

lintcode: 608-Two-Sum-II-Input-array-is-sorted

---

lintcode/two_pointers/587-Two-Sum-Unique-pairs/solution.py
lintcode/two_pointers/587-Two-Sum-Unique-pairs/test.py

- lintcode: 587-Two-Sum-Unique-pairs

lintcode: 587-Two-Sum-Unique-pairs

---

lintcode/two_pointers/533-Two-Sum-Closest-to-target/solution.py
lintcode/two_pointers/533-Two-Sum-Closest-to-target/test.py

- lintcode: 533-Two-Sum-Closest-to-target

lintcode: 533-Two-Sum-Closest-to-target

---

lintcode/two_pointers/57-3Sum/solution.py
lintcode/two_pointers/57-3Sum/test.py

lintcode: 57-3Sum

---

lintcode/two_pointers/31-Partition-Array/solution.py
lintcode/two_pointers/31-Partition-Array/test.py

- lintcode: 31-Partition-Array

lintcode: 31-Partition-Array

---

lintcode/two_pointers/373-Partition-Array-by-Odd-and-Even/solution.py
lintcode/two_pointers/373-Partition-Array-by-Odd-and-Even/test.py

- lintcode: 373-Partition-Array-by-Odd-and-Even

lintcode: 373-Partition-Array-by-Odd-and-Even

---

lintcode/two_pointers/49-Sort-Letters-by-Case/solution.py
lintcode/two_pointers/49-Sort-Letters-by-Case/test.py

- lintcode: 49-Sort-Letters-by-Case

lintcode: 49-Sort-Letters-by-Case

---

README.md

- doc: add doc on how to run on local machine

doc: add doc on how to run on local machine

---

lintcode/two_pointers/521-Remove-Duplicate-Numbers-in-Array/solution.py
lintcode/two_pointers/521-Remove-Duplicate-Numbers-in-Array/test.py

- lintcode: 521-Remove-Duplicate-Numbers-in-Array-by-Hash
- add test for this solution also

lintcode: 521-Remove-Duplicate-Numbers-in-Array-by-Hash
